name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o zaico-mcp-server-linux-amd64 ./cmd/zaico-mcp-server

      - name: Build for Linux (arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -o zaico-mcp-server-linux-arm64 ./cmd/zaico-mcp-server

      - name: Build for Linux (arm)
        run: |
          GOOS=linux GOARCH=arm go build -o zaico-mcp-server-linux-arm ./cmd/zaico-mcp-server

      - name: Build for macOS (amd64)
        run: |
          GOOS=darwin GOARCH=amd64 go build -o zaico-mcp-server-darwin-amd64 ./cmd/zaico-mcp-server

      - name: Build for macOS (arm64)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o zaico-mcp-server-darwin-arm64 ./cmd/zaico-mcp-server

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o zaico-mcp-server-windows-amd64.exe ./cmd/zaico-mcp-server

      - name: Build for Windows (arm64)
        run: |
          GOOS=windows GOARCH=arm64 go build -o zaico-mcp-server-windows-arm64.exe ./cmd/zaico-mcp-server

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            zaico-mcp-server-linux-amd64
            zaico-mcp-server-linux-arm64
            zaico-mcp-server-linux-arm
            zaico-mcp-server-darwin-amd64
            zaico-mcp-server-darwin-arm64
            zaico-mcp-server-windows-amd64.exe
            zaico-mcp-server-windows-arm64.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 